
package com.app.client.stubs.mtom;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MOTMStream", targetNamespace = "http://example.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MOTMStream {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "fileUpload", targetNamespace = "http://example.org", className = "com.app.client.stubs.mtom.FileUpload")
    @ResponseWrapper(localName = "fileUploadResponse", targetNamespace = "http://example.org", className = "com.app.client.stubs.mtom.FileUploadResponse")
    @Action(input = "http://example.org/MOTMStream/fileUploadRequest", output = "http://example.org/MOTMStream/fileUploadResponse")
    public void fileUpload(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        DataHandler arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fileDownload", targetNamespace = "http://example.org", className = "com.app.client.stubs.mtom.FileDownload")
    @ResponseWrapper(localName = "fileDownloadResponse", targetNamespace = "http://example.org", className = "com.app.client.stubs.mtom.FileDownloadResponse")
    @Action(input = "http://example.org/MOTMStream/fileDownloadRequest", output = "http://example.org/MOTMStream/fileDownloadResponse")
    public DataHandler fileDownload(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
