
package com.app.client.stubs.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MtomStreamingService", targetNamespace = "http://example.org", wsdlLocation = "http://localhost:9090/StreamingMTOMService?wsdl")
public class MtomStreamingService
    extends Service
{

    private final static URL MTOMSTREAMINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTOMSTREAMINGSERVICE_EXCEPTION;
    private final static QName MTOMSTREAMINGSERVICE_QNAME = new QName("http://example.org", "MtomStreamingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/StreamingMTOMService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTOMSTREAMINGSERVICE_WSDL_LOCATION = url;
        MTOMSTREAMINGSERVICE_EXCEPTION = e;
    }

    public MtomStreamingService() {
        super(__getWsdlLocation(), MTOMSTREAMINGSERVICE_QNAME);
    }

    public MtomStreamingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTOMSTREAMINGSERVICE_QNAME, features);
    }

    public MtomStreamingService(URL wsdlLocation) {
        super(wsdlLocation, MTOMSTREAMINGSERVICE_QNAME);
    }

    public MtomStreamingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTOMSTREAMINGSERVICE_QNAME, features);
    }

    public MtomStreamingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MtomStreamingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MOTMStream
     */
    @WebEndpoint(name = "MTOMPort")
    public MOTMStream getMTOMPort() {
        return super.getPort(new QName("http://example.org", "MTOMPort"), MOTMStream.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MOTMStream
     */
    @WebEndpoint(name = "MTOMPort")
    public MOTMStream getMTOMPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.org", "MTOMPort"), MOTMStream.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTOMSTREAMINGSERVICE_EXCEPTION!= null) {
            throw MTOMSTREAMINGSERVICE_EXCEPTION;
        }
        return MTOMSTREAMINGSERVICE_WSDL_LOCATION;
    }

}
