//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 05:17:37 PM IST 
//


package com.ericsson.mdc.ws.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responseHeader" type="{http://mdc.ericsson.com/ws/soap/}responseHeader"/>
 *         &lt;element name="detailedResourceDetails" type="{http://mdc.ericsson.com/ws/soap/}detailedResourceDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseHeader",
    "detailedResourceDetails"
})
@XmlRootElement(name = "getDetailedResourceDetailsResponse")
public class GetDetailedResourceDetailsResponse {

    @XmlElement(required = true)
    protected ResponseHeader responseHeader;
    @XmlElement(required = true)
    protected DetailedResourceDetails detailedResourceDetails;

    /**
     * Gets the value of the responseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseHeader }
     *     
     */
    public ResponseHeader getResponseHeader() {
        return responseHeader;
    }

    /**
     * Sets the value of the responseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseHeader }
     *     
     */
    public void setResponseHeader(ResponseHeader value) {
        this.responseHeader = value;
    }

    /**
     * Gets the value of the detailedResourceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DetailedResourceDetails }
     *     
     */
    public DetailedResourceDetails getDetailedResourceDetails() {
        return detailedResourceDetails;
    }

    /**
     * Sets the value of the detailedResourceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailedResourceDetails }
     *     
     */
    public void setDetailedResourceDetails(DetailedResourceDetails value) {
        this.detailedResourceDetails = value;
    }

}
