//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 05:17:37 PM IST 
//


package com.ericsson.mdc.ws.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ericsson.mdc.ws.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ericsson.mdc.ws.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserRegistrationResponse }
     * 
     */
    public UserRegistrationResponse createUserRegistrationResponse() {
        return new UserRegistrationResponse();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link ChangePasswordResponse }
     * 
     */
    public ChangePasswordResponse createChangePasswordResponse() {
        return new ChangePasswordResponse();
    }

    /**
     * Create an instance of {@link GetResourcesByRoleResponse }
     * 
     */
    public GetResourcesByRoleResponse createGetResourcesByRoleResponse() {
        return new GetResourcesByRoleResponse();
    }

    /**
     * Create an instance of {@link GetCurrentActivityRequest }
     * 
     */
    public GetCurrentActivityRequest createGetCurrentActivityRequest() {
        return new GetCurrentActivityRequest();
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link GetBasicResourceDetailsRequest }
     * 
     */
    public GetBasicResourceDetailsRequest createGetBasicResourceDetailsRequest() {
        return new GetBasicResourceDetailsRequest();
    }

    /**
     * Create an instance of {@link UserAuthenticationResponse }
     * 
     */
    public UserAuthenticationResponse createUserAuthenticationResponse() {
        return new UserAuthenticationResponse();
    }

    /**
     * Create an instance of {@link UserAuthenticationData }
     * 
     */
    public UserAuthenticationData createUserAuthenticationData() {
        return new UserAuthenticationData();
    }

    /**
     * Create an instance of {@link GetResourcesByManagerRequest }
     * 
     */
    public GetResourcesByManagerRequest createGetResourcesByManagerRequest() {
        return new GetResourcesByManagerRequest();
    }

    /**
     * Create an instance of {@link ChangePasswordRequest }
     * 
     */
    public ChangePasswordRequest createChangePasswordRequest() {
        return new ChangePasswordRequest();
    }

    /**
     * Create an instance of {@link GetCurrentActivityResponse }
     * 
     */
    public GetCurrentActivityResponse createGetCurrentActivityResponse() {
        return new GetCurrentActivityResponse();
    }

    /**
     * Create an instance of {@link CurrentActivityDetails }
     * 
     */
    public CurrentActivityDetails createCurrentActivityDetails() {
        return new CurrentActivityDetails();
    }

    /**
     * Create an instance of {@link GetAllActivityResponse }
     * 
     */
    public GetAllActivityResponse createGetAllActivityResponse() {
        return new GetAllActivityResponse();
    }

    /**
     * Create an instance of {@link GetDetailedResourceDetailsResponse }
     * 
     */
    public GetDetailedResourceDetailsResponse createGetDetailedResourceDetailsResponse() {
        return new GetDetailedResourceDetailsResponse();
    }

    /**
     * Create an instance of {@link DetailedResourceDetails }
     * 
     */
    public DetailedResourceDetails createDetailedResourceDetails() {
        return new DetailedResourceDetails();
    }

    /**
     * Create an instance of {@link GetBasicResourceDetailsResponse }
     * 
     */
    public GetBasicResourceDetailsResponse createGetBasicResourceDetailsResponse() {
        return new GetBasicResourceDetailsResponse();
    }

    /**
     * Create an instance of {@link BasicResourceDetails }
     * 
     */
    public BasicResourceDetails createBasicResourceDetails() {
        return new BasicResourceDetails();
    }

    /**
     * Create an instance of {@link UpdateBasicResourceDetailsResponse }
     * 
     */
    public UpdateBasicResourceDetailsResponse createUpdateBasicResourceDetailsResponse() {
        return new UpdateBasicResourceDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateBasicResourceDetailsRequest }
     * 
     */
    public UpdateBasicResourceDetailsRequest createUpdateBasicResourceDetailsRequest() {
        return new UpdateBasicResourceDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllActivityRequest }
     * 
     */
    public GetAllActivityRequest createGetAllActivityRequest() {
        return new GetAllActivityRequest();
    }

    /**
     * Create an instance of {@link UserAuthenticationRequest }
     * 
     */
    public UserAuthenticationRequest createUserAuthenticationRequest() {
        return new UserAuthenticationRequest();
    }

    /**
     * Create an instance of {@link UpdateCurrentActivityRequest }
     * 
     */
    public UpdateCurrentActivityRequest createUpdateCurrentActivityRequest() {
        return new UpdateCurrentActivityRequest();
    }

    /**
     * Create an instance of {@link GetDetailedResourceDetailsByManagerResponse }
     * 
     */
    public GetDetailedResourceDetailsByManagerResponse createGetDetailedResourceDetailsByManagerResponse() {
        return new GetDetailedResourceDetailsByManagerResponse();
    }

    /**
     * Create an instance of {@link UpdateCurrentActivityResponse }
     * 
     */
    public UpdateCurrentActivityResponse createUpdateCurrentActivityResponse() {
        return new UpdateCurrentActivityResponse();
    }

    /**
     * Create an instance of {@link UpdateDetailedResourceDetailsResponse }
     * 
     */
    public UpdateDetailedResourceDetailsResponse createUpdateDetailedResourceDetailsResponse() {
        return new UpdateDetailedResourceDetailsResponse();
    }

    /**
     * Create an instance of {@link UserRegistrationRequest }
     * 
     */
    public UserRegistrationRequest createUserRegistrationRequest() {
        return new UserRegistrationRequest();
    }

    /**
     * Create an instance of {@link UpdateDetailedResourceDetailsRequest }
     * 
     */
    public UpdateDetailedResourceDetailsRequest createUpdateDetailedResourceDetailsRequest() {
        return new UpdateDetailedResourceDetailsRequest();
    }

    /**
     * Create an instance of {@link GetResourcesByRoleRequest }
     * 
     */
    public GetResourcesByRoleRequest createGetResourcesByRoleRequest() {
        return new GetResourcesByRoleRequest();
    }

    /**
     * Create an instance of {@link GetDetailedResourceDetailsByManagerRequest }
     * 
     */
    public GetDetailedResourceDetailsByManagerRequest createGetDetailedResourceDetailsByManagerRequest() {
        return new GetDetailedResourceDetailsByManagerRequest();
    }

    /**
     * Create an instance of {@link GetResourcesByManagerResponse }
     * 
     */
    public GetResourcesByManagerResponse createGetResourcesByManagerResponse() {
        return new GetResourcesByManagerResponse();
    }

    /**
     * Create an instance of {@link GetDetailedResourceDetailsRequest }
     * 
     */
    public GetDetailedResourceDetailsRequest createGetDetailedResourceDetailsRequest() {
        return new GetDetailedResourceDetailsRequest();
    }

}
