//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="IMSI" type="{http://schemas.ericsson.com/ma/cai/1.0/}IMSIType"/>
 *         &lt;element name="MSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType"/>
 *         &lt;element name="PROFILE" type="{http://schemas.ericsson.com/ma/cai/1.0/}int"/>
 *         &lt;element name="AUTHD" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="CAT" type="{http://schemas.ericsson.com/ma/cai/1.0/}CategoryType" minOccurs="0"/>
 *         &lt;element name="AMSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="TS11" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="TS21" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="TS22" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="TS61" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="TS62" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS21" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS22" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS23" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS24" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS25" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS26" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS2F" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS2G" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS31" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS32" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS33" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS34" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS3F" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BS3G" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="OBI" type="{http://schemas.ericsson.com/ma/cai/1.0/}OBIType" minOccurs="0"/>
 *         &lt;element name="OBO" type="{http://schemas.ericsson.com/ma/cai/1.0/}OBOType" minOccurs="0"/>
 *         &lt;element name="OBR" type="{http://schemas.ericsson.com/ma/cai/1.0/}OBRType" minOccurs="0"/>
 *         &lt;element name="OBOPRE" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="OBOPRI" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="OBA" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="SOCB" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="BAIC" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="BAOC" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="BICRO" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="BOIC" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="BOIEXH" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="OBSSM" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="CAW" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="HOLD" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="MPTY" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="SOCLIP" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="SOCLIR" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="SOCOLP" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="CLIP" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="CLIR" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="COLP" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="COLR" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="SODCF" type="{http://schemas.ericsson.com/ma/cai/1.0/}SODCFType" minOccurs="0"/>
 *         &lt;element name="SOCFU" type="{http://schemas.ericsson.com/ma/cai/1.0/}SODCFType" minOccurs="0"/>
 *         &lt;element name="SOCFB" type="{http://schemas.ericsson.com/ma/cai/1.0/}SODCFType" minOccurs="0"/>
 *         &lt;element name="SOCFRY" type="{http://schemas.ericsson.com/ma/cai/1.0/}SODCFType" minOccurs="0"/>
 *         &lt;element name="SOCFRC" type="{http://schemas.ericsson.com/ma/cai/1.0/}SODCFType" minOccurs="0"/>
 *         &lt;element name="DCF" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="CFU" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="CFB" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="CFNRY" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="CFNRC" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="NAM" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="GPRS" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMapsOperation" minOccurs="0"/>
 *         &lt;element name="CAMEL" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMapsOperation" minOccurs="0"/>
 *         &lt;element name="OICK" type="{http://schemas.ericsson.com/ma/cai/1.0/}ICKType" minOccurs="0"/>
 *         &lt;element name="TICK" type="{http://schemas.ericsson.com/ma/cai/1.0/}ICKType" minOccurs="0"/>
 *         &lt;element name="OCSI" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="TCSI" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="CUGSUB" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMapsOperation" minOccurs="0"/>
 *         &lt;element name="CUG" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMapsOperation" minOccurs="0"/>
 *         &lt;element name="PWD" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="LOC" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="STYPE" type="{http://schemas.ericsson.com/ma/cai/1.0/}SType" minOccurs="0"/>
 *         &lt;element name="TEARDOWN" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType" minOccurs="0"/>
 *         &lt;element name="SCHAR" type="{http://schemas.ericsson.com/ma/cai/1.0/}int" minOccurs="0"/>
 *         &lt;element name="USERTYPE" type="{http://schemas.ericsson.com/ma/cai/1.0/}UserType" minOccurs="0"/>
 *         &lt;element name="ARD" type="{http://schemas.ericsson.com/ma/cai/1.0/}ARDType" minOccurs="0"/>
 *         &lt;element name="CSP" type="{http://schemas.ericsson.com/ma/cai/1.0/}int" minOccurs="0"/>
 *         &lt;element name="LTE" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMapsOperation" minOccurs="0"/>
 *         &lt;element name="VMS" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="EPSDATA" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMapsOperation" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imsiOrMSISDNOrPROFILE"
})
@XmlRootElement(name = "CreateMOVILHLRSUB")
public class CreateMOVILHLRSUB {

    @XmlElementRefs({
        @XmlElementRef(name = "OBO", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TICK", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CLIR", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "EPSDATA", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS24", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BICRO", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TS22", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AUTHD", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OBA", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ARD", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "IMSI", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "VMS", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NAM", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GPRS", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CAMEL", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CFU", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS33", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS2G", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MSISDN", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TS62", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS31", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS32", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CAW", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LOC", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OICK", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PWD", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BOIEXH", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SODCF", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CFNRY", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LTE", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS2F", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "COLR", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BAIC", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCFB", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS25", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PROFILE", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CUG", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCFRY", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS21", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CUGSUB", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS34", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AMSISDN", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "STYPE", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BOIC", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CSP", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CFB", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TS61", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS26", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCOLP", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OBI", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CLIP", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TS21", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCFRC", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TCSI", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "USERTYPE", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BAOC", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SCHAR", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS23", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "HOLD", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CFNRC", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OBOPRE", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "COLP", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TEARDOWN", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS3G", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCLIR", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DCF", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CAT", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCB", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS22", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BS3F", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OBSSM", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OBOPRI", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCFU", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OCSI", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OBR", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SOCLIP", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TS11", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MPTY", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> imsiOrMSISDNOrPROFILE;

    /**
     * Gets the value of the imsiOrMSISDNOrPROFILE property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imsiOrMSISDNOrPROFILE property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIMSIOrMSISDNOrPROFILE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMapsOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMapsOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMapsOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMapsOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMapsOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMapsOperation }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMaps }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getIMSIOrMSISDNOrPROFILE() {
        if (imsiOrMSISDNOrPROFILE == null) {
            imsiOrMSISDNOrPROFILE = new ArrayList<JAXBElement<?>>();
        }
        return this.imsiOrMSISDNOrPROFILE;
    }

}
