//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IMSI" type="{http://schemas.ericsson.com/ma/cai/1.0/}IMSIType" minOccurs="0"/>
 *         &lt;element name="KI" type="{http://schemas.ericsson.com/ma/cai/1.0/}KIType" minOccurs="0"/>
 *         &lt;element name="A38" type="{http://schemas.ericsson.com/ma/cai/1.0/}A38Type" minOccurs="0"/>
 *         &lt;element name="A4" type="{http://schemas.ericsson.com/ma/cai/1.0/}A4Type" minOccurs="0"/>
 *         &lt;element name="ADKEY" type="{http://schemas.ericsson.com/ma/cai/1.0/}ADKeyType" minOccurs="0"/>
 *         &lt;element name="AKATYPE" type="{http://schemas.ericsson.com/ma/cai/1.0/}AkaType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imsi",
    "ki",
    "a38",
    "a4",
    "adkey",
    "akatype"
})
@XmlRootElement(name = "GetResponseMOVILAUCSUB")
public class GetResponseMOVILAUCSUB {

    @XmlElement(name = "IMSI")
    protected BigInteger imsi;
    @XmlElement(name = "KI")
    protected String ki;
    @XmlElement(name = "A38")
    @XmlSchemaType(name = "integer")
    protected Integer a38;
    @XmlElement(name = "A4")
    @XmlSchemaType(name = "integer")
    protected Integer a4;
    @XmlElement(name = "ADKEY")
    @XmlSchemaType(name = "integer")
    protected Integer adkey;
    @XmlElement(name = "AKATYPE")
    protected String akatype;

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIMSI(BigInteger value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the ki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKI() {
        return ki;
    }

    /**
     * Sets the value of the ki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKI(String value) {
        this.ki = value;
    }

    /**
     * Gets the value of the a38 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getA38() {
        return a38;
    }

    /**
     * Sets the value of the a38 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setA38(Integer value) {
        this.a38 = value;
    }

    /**
     * Gets the value of the a4 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getA4() {
        return a4;
    }

    /**
     * Sets the value of the a4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setA4(Integer value) {
        this.a4 = value;
    }

    /**
     * Gets the value of the adkey property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getADKEY() {
        return adkey;
    }

    /**
     * Sets the value of the adkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setADKEY(Integer value) {
        this.adkey = value;
    }

    /**
     * Gets the value of the akatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAKATYPE() {
        return akatype;
    }

    /**
     * Sets the value of the akatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAKATYPE(String value) {
        this.akatype = value;
    }

}
