//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType"/>
 *         &lt;element name="Status" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="ServiceClass" type="{http://schemas.ericsson.com/ma/cai/1.0/}int" minOccurs="0"/>
 *         &lt;element name="ServiceClassList" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="AccountBalance" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="OrigServiceClass" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="TempServiceClassExpDate" type="{http://schemas.ericsson.com/ma/cai/1.0/}AIRDateType" minOccurs="0"/>
 *         &lt;element name="PinCode" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="SupervisionPeriodExpiryDate" type="{http://schemas.ericsson.com/ma/cai/1.0/}AIRDateType" minOccurs="0"/>
 *         &lt;element name="ServiceFeePeriodExpiryDate" type="{http://schemas.ericsson.com/ma/cai/1.0/}AIRDateType" minOccurs="0"/>
 *         &lt;element name="ActivationDate" type="{http://schemas.ericsson.com/ma/cai/1.0/}AIRDateType" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://schemas.ericsson.com/ma/cai/1.0/}CurrencyType" minOccurs="0"/>
 *         &lt;element name="DedicatedAccounts" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *         &lt;element name="Accumulators" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Offers" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PAM" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SHAREACCOUNT" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FAF" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CommunityIdList" type="{http://schemas.ericsson.com/ma/cai/1.0/}ValueMaps" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdn",
    "status",
    "serviceClass",
    "serviceClassList",
    "accountBalance",
    "origServiceClass",
    "tempServiceClassExpDate",
    "pinCode",
    "supervisionPeriodExpiryDate",
    "serviceFeePeriodExpiryDate",
    "activationDate",
    "currency",
    "dedicatedAccounts",
    "accumulators",
    "offers",
    "pam",
    "shareaccount",
    "faf",
    "communityIdList"
})
@XmlRootElement(name = "GetResponseMOVILPOSSUB")
public class GetResponseMOVILPOSSUB {

    @XmlElement(name = "MSISDN", required = true)
    protected BigInteger msisdn;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "ServiceClass")
    protected BigInteger serviceClass;
    @XmlElement(name = "ServiceClassList")
    protected String serviceClassList;
    @XmlElement(name = "AccountBalance")
    protected String accountBalance;
    @XmlElement(name = "OrigServiceClass")
    protected String origServiceClass;
    @XmlElement(name = "TempServiceClassExpDate")
    protected BigInteger tempServiceClassExpDate;
    @XmlElement(name = "PinCode")
    protected String pinCode;
    @XmlElement(name = "SupervisionPeriodExpiryDate")
    protected BigInteger supervisionPeriodExpiryDate;
    @XmlElement(name = "ServiceFeePeriodExpiryDate")
    protected BigInteger serviceFeePeriodExpiryDate;
    @XmlElement(name = "ActivationDate")
    protected BigInteger activationDate;
    @XmlElement(name = "Currency")
    @XmlSchemaType(name = "string")
    protected CurrencyType currency;
    @XmlElement(name = "DedicatedAccounts")
    protected ValueMaps dedicatedAccounts;
    @XmlElement(name = "Accumulators")
    protected List<ValueMaps> accumulators;
    @XmlElement(name = "Offers")
    protected List<ValueMaps> offers;
    @XmlElement(name = "PAM")
    protected List<ValueMaps> pam;
    @XmlElement(name = "SHAREACCOUNT")
    protected List<ValueMaps> shareaccount;
    @XmlElement(name = "FAF")
    protected List<ValueMaps> faf;
    @XmlElement(name = "CommunityIdList")
    protected ValueMaps communityIdList;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMSISDN(BigInteger value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the serviceClass property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServiceClass() {
        return serviceClass;
    }

    /**
     * Sets the value of the serviceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServiceClass(BigInteger value) {
        this.serviceClass = value;
    }

    /**
     * Gets the value of the serviceClassList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceClassList() {
        return serviceClassList;
    }

    /**
     * Sets the value of the serviceClassList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceClassList(String value) {
        this.serviceClassList = value;
    }

    /**
     * Gets the value of the accountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountBalance() {
        return accountBalance;
    }

    /**
     * Sets the value of the accountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountBalance(String value) {
        this.accountBalance = value;
    }

    /**
     * Gets the value of the origServiceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigServiceClass() {
        return origServiceClass;
    }

    /**
     * Sets the value of the origServiceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigServiceClass(String value) {
        this.origServiceClass = value;
    }

    /**
     * Gets the value of the tempServiceClassExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTempServiceClassExpDate() {
        return tempServiceClassExpDate;
    }

    /**
     * Sets the value of the tempServiceClassExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTempServiceClassExpDate(BigInteger value) {
        this.tempServiceClassExpDate = value;
    }

    /**
     * Gets the value of the pinCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinCode() {
        return pinCode;
    }

    /**
     * Sets the value of the pinCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinCode(String value) {
        this.pinCode = value;
    }

    /**
     * Gets the value of the supervisionPeriodExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSupervisionPeriodExpiryDate() {
        return supervisionPeriodExpiryDate;
    }

    /**
     * Sets the value of the supervisionPeriodExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSupervisionPeriodExpiryDate(BigInteger value) {
        this.supervisionPeriodExpiryDate = value;
    }

    /**
     * Gets the value of the serviceFeePeriodExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServiceFeePeriodExpiryDate() {
        return serviceFeePeriodExpiryDate;
    }

    /**
     * Sets the value of the serviceFeePeriodExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServiceFeePeriodExpiryDate(BigInteger value) {
        this.serviceFeePeriodExpiryDate = value;
    }

    /**
     * Gets the value of the activationDate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActivationDate() {
        return activationDate;
    }

    /**
     * Sets the value of the activationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setActivationDate(BigInteger value) {
        this.activationDate = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     */
    public void setCurrency(CurrencyType value) {
        this.currency = value;
    }

    /**
     * Gets the value of the dedicatedAccounts property.
     * 
     * @return
     *     possible object is
     *     {@link ValueMaps }
     *     
     */
    public ValueMaps getDedicatedAccounts() {
        return dedicatedAccounts;
    }

    /**
     * Sets the value of the dedicatedAccounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueMaps }
     *     
     */
    public void setDedicatedAccounts(ValueMaps value) {
        this.dedicatedAccounts = value;
    }

    /**
     * Gets the value of the accumulators property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accumulators property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccumulators().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueMaps }
     * 
     * 
     */
    public List<ValueMaps> getAccumulators() {
        if (accumulators == null) {
            accumulators = new ArrayList<ValueMaps>();
        }
        return this.accumulators;
    }

    /**
     * Gets the value of the offers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueMaps }
     * 
     * 
     */
    public List<ValueMaps> getOffers() {
        if (offers == null) {
            offers = new ArrayList<ValueMaps>();
        }
        return this.offers;
    }

    /**
     * Gets the value of the pam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPAM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueMaps }
     * 
     * 
     */
    public List<ValueMaps> getPAM() {
        if (pam == null) {
            pam = new ArrayList<ValueMaps>();
        }
        return this.pam;
    }

    /**
     * Gets the value of the shareaccount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shareaccount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSHAREACCOUNT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueMaps }
     * 
     * 
     */
    public List<ValueMaps> getSHAREACCOUNT() {
        if (shareaccount == null) {
            shareaccount = new ArrayList<ValueMaps>();
        }
        return this.shareaccount;
    }

    /**
     * Gets the value of the faf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFAF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValueMaps }
     * 
     * 
     */
    public List<ValueMaps> getFAF() {
        if (faf == null) {
            faf = new ArrayList<ValueMaps>();
        }
        return this.faf;
    }

    /**
     * Gets the value of the communityIdList property.
     * 
     * @return
     *     possible object is
     *     {@link ValueMaps }
     *     
     */
    public ValueMaps getCommunityIdList() {
        return communityIdList;
    }

    /**
     * Sets the value of the communityIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueMaps }
     *     
     */
    public void setCommunityIdList(ValueMaps value) {
        this.communityIdList = value;
    }

}
