//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="MSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType"/>
 *         &lt;element name="TransactionAmount" type="{http://schemas.ericsson.com/ma/cai/1.0/}string"/>
 *         &lt;element name="PaymentProfile" type="{http://schemas.ericsson.com/ma/cai/1.0/}PaymentProfileType"/>
 *         &lt;element name="CurrencyType" type="{http://schemas.ericsson.com/ma/cai/1.0/}CurrencyType"/>
 *         &lt;element name="TIMEOUT" type="{http://schemas.ericsson.com/ma/cai/1.0/}int" minOccurs="0"/>
 *         &lt;element name="OperatorID" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="REASONID" type="{http://schemas.ericsson.com/ma/cai/1.0/}ReasonType" minOccurs="0"/>
 *         &lt;element name="APPINFO" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdnOrTransactionAmountOrPaymentProfile"
})
@XmlRootElement(name = "GetRVIRTUAL")
public class GetRVIRTUAL {

    @XmlElementRefs({
        @XmlElementRef(name = "TIMEOUT", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MSISDN", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "REASONID", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "APPINFO", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PaymentProfile", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "OperatorID", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TransactionAmount", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CurrencyType", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> msisdnOrTransactionAmountOrPaymentProfile;

    /**
     * Gets the value of the msisdnOrTransactionAmountOrPaymentProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msisdnOrTransactionAmountOrPaymentProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMSISDNOrTransactionAmountOrPaymentProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link CurrencyType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getMSISDNOrTransactionAmountOrPaymentProfile() {
        if (msisdnOrTransactionAmountOrPaymentProfile == null) {
            msisdnOrTransactionAmountOrPaymentProfile = new ArrayList<JAXBElement<?>>();
        }
        return this.msisdnOrTransactionAmountOrPaymentProfile;
    }

}
