//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="AccountBalanceBefore" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="AccountBalance" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="TransactionAmount" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="PaymentProfile" type="{http://schemas.ericsson.com/ma/cai/1.0/}PaymentProfileType" minOccurs="0"/>
 *         &lt;element name="CurrencyType" type="{http://schemas.ericsson.com/ma/cai/1.0/}CurrencyType" minOccurs="0"/>
 *         &lt;element name="SupervisionPeriodExpiryDateBefore" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="ServiceFeePeriodExpiryDateBefore" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="SupervisionPeriodExpiryDate" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="ServiceFeePeriodExpiryDate" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="ResponseTime" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="OperatorID" type="{http://schemas.ericsson.com/ma/cai/1.0/}CurrencyType" minOccurs="0"/>
 *         &lt;element name="REASONID" type="{http://schemas.ericsson.com/ma/cai/1.0/}ReasonType" minOccurs="0"/>
 *         &lt;element name="APPINFO" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="TIMEOUT" type="{http://schemas.ericsson.com/ma/cai/1.0/}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdn",
    "status",
    "accountBalanceBefore",
    "accountBalance",
    "transactionAmount",
    "paymentProfile",
    "currencyType",
    "supervisionPeriodExpiryDateBefore",
    "serviceFeePeriodExpiryDateBefore",
    "supervisionPeriodExpiryDate",
    "serviceFeePeriodExpiryDate",
    "responseTime",
    "operatorID",
    "reasonid",
    "appinfo",
    "timeout"
})
@XmlRootElement(name = "GetResponseRVIRTUAL")
public class GetResponseRVIRTUAL {

    @XmlElement(name = "MSISDN")
    protected BigInteger msisdn;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "AccountBalanceBefore")
    protected String accountBalanceBefore;
    @XmlElement(name = "AccountBalance")
    protected String accountBalance;
    @XmlElement(name = "TransactionAmount")
    protected String transactionAmount;
    @XmlElement(name = "PaymentProfile")
    protected BigInteger paymentProfile;
    @XmlElement(name = "CurrencyType")
    @XmlSchemaType(name = "string")
    protected CurrencyType currencyType;
    @XmlElement(name = "SupervisionPeriodExpiryDateBefore")
    protected String supervisionPeriodExpiryDateBefore;
    @XmlElement(name = "ServiceFeePeriodExpiryDateBefore")
    protected String serviceFeePeriodExpiryDateBefore;
    @XmlElement(name = "SupervisionPeriodExpiryDate")
    protected String supervisionPeriodExpiryDate;
    @XmlElement(name = "ServiceFeePeriodExpiryDate")
    protected String serviceFeePeriodExpiryDate;
    @XmlElement(name = "ResponseTime")
    protected String responseTime;
    @XmlElement(name = "OperatorID")
    @XmlSchemaType(name = "string")
    protected CurrencyType operatorID;
    @XmlElement(name = "REASONID")
    @XmlSchemaType(name = "integer")
    protected Integer reasonid;
    @XmlElement(name = "APPINFO")
    protected String appinfo;
    @XmlElement(name = "TIMEOUT")
    protected BigInteger timeout;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMSISDN(BigInteger value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the accountBalanceBefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountBalanceBefore() {
        return accountBalanceBefore;
    }

    /**
     * Sets the value of the accountBalanceBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountBalanceBefore(String value) {
        this.accountBalanceBefore = value;
    }

    /**
     * Gets the value of the accountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountBalance() {
        return accountBalance;
    }

    /**
     * Sets the value of the accountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountBalance(String value) {
        this.accountBalance = value;
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionAmount(String value) {
        this.transactionAmount = value;
    }

    /**
     * Gets the value of the paymentProfile property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentProfile() {
        return paymentProfile;
    }

    /**
     * Sets the value of the paymentProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentProfile(BigInteger value) {
        this.paymentProfile = value;
    }

    /**
     * Gets the value of the currencyType property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCurrencyType() {
        return currencyType;
    }

    /**
     * Sets the value of the currencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     */
    public void setCurrencyType(CurrencyType value) {
        this.currencyType = value;
    }

    /**
     * Gets the value of the supervisionPeriodExpiryDateBefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisionPeriodExpiryDateBefore() {
        return supervisionPeriodExpiryDateBefore;
    }

    /**
     * Sets the value of the supervisionPeriodExpiryDateBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisionPeriodExpiryDateBefore(String value) {
        this.supervisionPeriodExpiryDateBefore = value;
    }

    /**
     * Gets the value of the serviceFeePeriodExpiryDateBefore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceFeePeriodExpiryDateBefore() {
        return serviceFeePeriodExpiryDateBefore;
    }

    /**
     * Sets the value of the serviceFeePeriodExpiryDateBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceFeePeriodExpiryDateBefore(String value) {
        this.serviceFeePeriodExpiryDateBefore = value;
    }

    /**
     * Gets the value of the supervisionPeriodExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisionPeriodExpiryDate() {
        return supervisionPeriodExpiryDate;
    }

    /**
     * Sets the value of the supervisionPeriodExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisionPeriodExpiryDate(String value) {
        this.supervisionPeriodExpiryDate = value;
    }

    /**
     * Gets the value of the serviceFeePeriodExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceFeePeriodExpiryDate() {
        return serviceFeePeriodExpiryDate;
    }

    /**
     * Sets the value of the serviceFeePeriodExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceFeePeriodExpiryDate(String value) {
        this.serviceFeePeriodExpiryDate = value;
    }

    /**
     * Gets the value of the responseTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseTime() {
        return responseTime;
    }

    /**
     * Sets the value of the responseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseTime(String value) {
        this.responseTime = value;
    }

    /**
     * Gets the value of the operatorID property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getOperatorID() {
        return operatorID;
    }

    /**
     * Sets the value of the operatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     */
    public void setOperatorID(CurrencyType value) {
        this.operatorID = value;
    }

    /**
     * Gets the value of the reasonid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getREASONID() {
        return reasonid;
    }

    /**
     * Sets the value of the reasonid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setREASONID(Integer value) {
        this.reasonid = value;
    }

    /**
     * Gets the value of the appinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPINFO() {
        return appinfo;
    }

    /**
     * Sets the value of the appinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPINFO(String value) {
        this.appinfo = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTIMEOUT() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTIMEOUT(BigInteger value) {
        this.timeout = value;
    }

}
