//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VoucherSerialNumber" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="VoucherStatus" type="{http://schemas.ericsson.com/ma/cai/1.0/}VoucherStatusType" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://schemas.ericsson.com/ma/cai/1.0/}CurrencyType" minOccurs="0"/>
 *         &lt;element name="Agent" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="BatchID" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="OperatorID" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="TimeStamp" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="VoucherExpiryDate" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="VoucherGroup" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="VoucherValue" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "voucherSerialNumber",
    "voucherStatus",
    "currency",
    "agent",
    "batchID",
    "operatorID",
    "timeStamp",
    "voucherExpiryDate",
    "voucherGroup",
    "voucherValue"
})
@XmlRootElement(name = "GetResponseMOVILPPAYSUB")
public class GetResponseMOVILPPAYSUB {

    @XmlElement(name = "VoucherSerialNumber")
    protected String voucherSerialNumber;
    @XmlElement(name = "VoucherStatus")
    @XmlSchemaType(name = "integer")
    protected Integer voucherStatus;
    @XmlElement(name = "Currency")
    @XmlSchemaType(name = "string")
    protected CurrencyType currency;
    @XmlElement(name = "Agent")
    protected String agent;
    @XmlElement(name = "BatchID")
    protected String batchID;
    @XmlElement(name = "OperatorID")
    protected String operatorID;
    @XmlElement(name = "TimeStamp")
    protected String timeStamp;
    @XmlElement(name = "VoucherExpiryDate")
    protected String voucherExpiryDate;
    @XmlElement(name = "VoucherGroup")
    protected String voucherGroup;
    @XmlElement(name = "VoucherValue")
    protected String voucherValue;

    /**
     * Gets the value of the voucherSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherSerialNumber() {
        return voucherSerialNumber;
    }

    /**
     * Sets the value of the voucherSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherSerialNumber(String value) {
        this.voucherSerialNumber = value;
    }

    /**
     * Gets the value of the voucherStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVoucherStatus() {
        return voucherStatus;
    }

    /**
     * Sets the value of the voucherStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVoucherStatus(Integer value) {
        this.voucherStatus = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     */
    public void setCurrency(CurrencyType value) {
        this.currency = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgent(String value) {
        this.agent = value;
    }

    /**
     * Gets the value of the batchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchID() {
        return batchID;
    }

    /**
     * Sets the value of the batchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchID(String value) {
        this.batchID = value;
    }

    /**
     * Gets the value of the operatorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorID() {
        return operatorID;
    }

    /**
     * Sets the value of the operatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorID(String value) {
        this.operatorID = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the voucherExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherExpiryDate() {
        return voucherExpiryDate;
    }

    /**
     * Sets the value of the voucherExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherExpiryDate(String value) {
        this.voucherExpiryDate = value;
    }

    /**
     * Gets the value of the voucherGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherGroup() {
        return voucherGroup;
    }

    /**
     * Sets the value of the voucherGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherGroup(String value) {
        this.voucherGroup = value;
    }

    /**
     * Gets the value of the voucherValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherValue() {
        return voucherValue;
    }

    /**
     * Sets the value of the voucherValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherValue(String value) {
        this.voucherValue = value;
    }

}
