//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType" minOccurs="0"/>
 *         &lt;element name="IMSI" type="{http://schemas.ericsson.com/ma/cai/1.0/}IMSIType" minOccurs="0"/>
 *         &lt;element name="STATUS" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="IMEI" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="CELLID" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="CELLNAME" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *         &lt;element name="VLR" type="{http://schemas.ericsson.com/ma/cai/1.0/}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdn",
    "imsi",
    "status",
    "imei",
    "cellid",
    "cellname",
    "vlr"
})
@XmlRootElement(name = "GetResponseCONTROLSUB")
public class GetResponseCONTROLSUB {

    @XmlElement(name = "MSISDN")
    protected BigInteger msisdn;
    @XmlElement(name = "IMSI")
    protected BigInteger imsi;
    @XmlElement(name = "STATUS")
    protected String status;
    @XmlElement(name = "IMEI")
    protected String imei;
    @XmlElement(name = "CELLID")
    protected String cellid;
    @XmlElement(name = "CELLNAME")
    protected String cellname;
    @XmlElement(name = "VLR")
    protected String vlr;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMSISDN() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMSISDN(BigInteger value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the imsi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIMSI() {
        return imsi;
    }

    /**
     * Sets the value of the imsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIMSI(BigInteger value) {
        this.imsi = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the imei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMEI() {
        return imei;
    }

    /**
     * Sets the value of the imei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMEI(String value) {
        this.imei = value;
    }

    /**
     * Gets the value of the cellid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCELLID() {
        return cellid;
    }

    /**
     * Sets the value of the cellid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCELLID(String value) {
        this.cellid = value;
    }

    /**
     * Gets the value of the cellname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCELLNAME() {
        return cellname;
    }

    /**
     * Sets the value of the cellname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCELLNAME(String value) {
        this.cellname = value;
    }

    /**
     * Gets the value of the vlr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVLR() {
        return vlr;
    }

    /**
     * Sets the value of the vlr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVLR(String value) {
        this.vlr = value;
    }

}
