//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.ericsson.com/ma/cai/1.0/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.examples.xjc;
