//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element name="MSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType"/>
 *             &lt;element name="VoucherActivationCode" type="{http://schemas.ericsson.com/ma/cai/1.0/}string"/>
 *           &lt;/choice>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element name="VoucherSerialNumber" type="{http://schemas.ericsson.com/ma/cai/1.0/}string"/>
 *             &lt;element name="NewVoucherStatus" type="{http://schemas.ericsson.com/ma/cai/1.0/}VoucherStatusType"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdnOrVoucherActivationCode",
    "voucherSerialNumberOrNewVoucherStatus"
})
@XmlRootElement(name = "SetMOVILPPAYSUB")
public class SetMOVILPPAYSUB {

    @XmlElements({
        @XmlElement(name = "MSISDN", type = BigInteger.class),
        @XmlElement(name = "VoucherActivationCode", type = String.class)
    })
    protected List<Serializable> msisdnOrVoucherActivationCode;
    @XmlElements({
        @XmlElement(name = "VoucherSerialNumber", type = String.class),
        @XmlElement(name = "NewVoucherStatus", type = Integer.class)
    })
    protected List<Serializable> voucherSerialNumberOrNewVoucherStatus;

    /**
     * Gets the value of the msisdnOrVoucherActivationCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msisdnOrVoucherActivationCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMSISDNOrVoucherActivationCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getMSISDNOrVoucherActivationCode() {
        if (msisdnOrVoucherActivationCode == null) {
            msisdnOrVoucherActivationCode = new ArrayList<Serializable>();
        }
        return this.msisdnOrVoucherActivationCode;
    }

    /**
     * Gets the value of the voucherSerialNumberOrNewVoucherStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voucherSerialNumberOrNewVoucherStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoucherSerialNumberOrNewVoucherStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link Integer }
     * 
     * 
     */
    public List<Serializable> getVoucherSerialNumberOrNewVoucherStatus() {
        if (voucherSerialNumberOrNewVoucherStatus == null) {
            voucherSerialNumberOrNewVoucherStatus = new ArrayList<Serializable>();
        }
        return this.voucherSerialNumberOrNewVoucherStatus;
    }

}
