//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="MSISDN" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType"/>
 *         &lt;element name="USERTYPE" type="{http://schemas.ericsson.com/ma/cai/1.0/}UserType"/>
 *         &lt;element name="FORWARDTO" type="{http://schemas.ericsson.com/ma/cai/1.0/}MSISDNType"/>
 *         &lt;element name="BARRING" type="{http://schemas.ericsson.com/ma/cai/1.0/}ServiceStatusType" minOccurs="0"/>
 *         &lt;element name="SMSBARRING" type="{http://schemas.ericsson.com/ma/cai/1.0/}ServiceStatusType" minOccurs="0"/>
 *         &lt;element name="TS21" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType"/>
 *         &lt;element name="TS22" type="{http://schemas.ericsson.com/ma/cai/1.0/}ProvisionType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msisdnOrUSERTYPEOrFORWARDTO"
})
@XmlRootElement(name = "SetTRACESUB")
public class SetTRACESUB {

    @XmlElementRefs({
        @XmlElementRef(name = "MSISDN", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "FORWARDTO", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TS21", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TS22", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "USERTYPE", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BARRING", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SMSBARRING", namespace = "http://schemas.ericsson.com/ma/cai/1.0/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> msisdnOrUSERTYPEOrFORWARDTO;

    /**
     * Gets the value of the msisdnOrUSERTYPEOrFORWARDTO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msisdnOrUSERTYPEOrFORWARDTO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMSISDNOrUSERTYPEOrFORWARDTO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getMSISDNOrUSERTYPEOrFORWARDTO() {
        if (msisdnOrUSERTYPEOrFORWARDTO == null) {
            msisdnOrUSERTYPEOrFORWARDTO = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.msisdnOrUSERTYPEOrFORWARDTO;
    }

}
