//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 05:37:56 PM IST 
//


package com.examples.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatusType">
 *   &lt;restriction base="{http://schemas.ericsson.com/ma/cai/1.0/}string">
 *     &lt;enumeration value="Block"/>
 *     &lt;enumeration value="Unblock"/>
 *     &lt;enumeration value="BlockRefill"/>
 *     &lt;enumeration value="UnblockRefill"/>
 *     &lt;enumeration value="Activate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StatusType")
@XmlEnum
public enum StatusType {

    @XmlEnumValue("Block")
    BLOCK("Block"),
    @XmlEnumValue("Unblock")
    UNBLOCK("Unblock"),
    @XmlEnumValue("BlockRefill")
    BLOCK_REFILL("BlockRefill"),
    @XmlEnumValue("UnblockRefill")
    UNBLOCK_REFILL("UnblockRefill"),
    @XmlEnumValue("Activate")
    ACTIVATE("Activate");
    private final String value;

    StatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusType fromValue(String v) {
        for (StatusType c: StatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
