
package com.soap.client.mobilewebservice.clientgen;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobileService", targetNamespace = "http://webservice.service.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileService {


    /**
     * 
     * @throws MobileSubscriptionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "throwError", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.ThrowError")
    @ResponseWrapper(localName = "throwErrorResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.ThrowErrorResponse")
    @Action(input = "http://webservice.service.soap.com/MobileService/throwErrorRequest", output = "http://webservice.service.soap.com/MobileService/throwErrorResponse", fault = {
        @FaultAction(className = MobileSubscriptionException_Exception.class, value = "http://webservice.service.soap.com/MobileService/throwError/Fault/MobileSubscriptionException")
    })
    public void throwError()
        throws MobileSubscriptionException_Exception
    ;

    /**
     * 
     * @param createSubscriberRequest
     * @throws MobileSubscriptionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createSubscriber", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.CreateSubscriber")
    @ResponseWrapper(localName = "createSubscriberResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.CreateSubscriberResponse")
    @Action(input = "http://webservice.service.soap.com/MobileService/createSubscriberRequest", output = "http://webservice.service.soap.com/MobileService/createSubscriberResponse", fault = {
        @FaultAction(className = MobileSubscriptionException_Exception.class, value = "http://webservice.service.soap.com/MobileService/createSubscriber/Fault/MobileSubscriptionException")
    })
    public void createSubscriber(
        @WebParam(name = "createSubscriberRequest", targetNamespace = "")
        SubscriberData createSubscriberRequest)
        throws MobileSubscriptionException_Exception
    ;

    /**
     * 
     * @param credentials
     * @param parameters
     * @return
     *     returns com.soap.client.mobilewebservice.clientgen.CreateSubscriberSecureResponse
     * @throws MobileSubscriptionException_Exception
     * @throws SecurityException_Exception
     */
    @WebMethod
    @WebResult(name = "createSubscriberSecureResponse", targetNamespace = "http://webservice.service.soap.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://webservice.service.soap.com/MobileService/createSubscriberSecureRequest", output = "http://webservice.service.soap.com/MobileService/createSubscriberSecureResponse", fault = {
        @FaultAction(className = MobileSubscriptionException_Exception.class, value = "http://webservice.service.soap.com/MobileService/createSubscriberSecure/Fault/MobileSubscriptionException"),
        @FaultAction(className = SecurityException_Exception.class, value = "http://webservice.service.soap.com/MobileService/createSubscriberSecure/Fault/SecurityException")
    })
    public CreateSubscriberSecureResponse createSubscriberSecure(
        @WebParam(name = "createSubscriberSecure", targetNamespace = "http://webservice.service.soap.com/", partName = "parameters")
        CreateSubscriberSecure parameters,
        @WebParam(name = "Credentials", targetNamespace = "http://webservice.service.soap.com/", header = true, partName = "Credentials")
        SecurityDetails credentials)
        throws MobileSubscriptionException_Exception, SecurityException_Exception
    ;

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "greetingsMessage", targetNamespace = "")
    @RequestWrapper(localName = "greetUser", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.GreetUser")
    @ResponseWrapper(localName = "greetUserResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.GreetUserResponse")
    @Action(input = "http://webservice.service.soap.com/MobileService/greetUserRequest", output = "http://webservice.service.soap.com/MobileService/greetUserResponse")
    public String greetUser(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param tokenvalue
     * @param password
     * @param parameters
     * @param username
     * @return
     *     returns com.soap.client.mobilewebservice.clientgen.GetSecureTokenResponse
     */
    @WebMethod
    @WebResult(name = "getSecureTokenResponse", targetNamespace = "http://webservice.service.soap.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://webservice.service.soap.com/MobileService/getSecureTokenRequest", output = "http://webservice.service.soap.com/MobileService/getSecureTokenResponse")
    public GetSecureTokenResponse getSecureToken(
        @WebParam(name = "getSecureToken", targetNamespace = "http://webservice.service.soap.com/", partName = "parameters")
        GetSecureToken parameters,
        @WebParam(name = "username", targetNamespace = "http://webservice.service.soap.com/", header = true, mode = WebParam.Mode.INOUT, partName = "username")
        Holder<String> username,
        @WebParam(name = "password", targetNamespace = "http://webservice.service.soap.com/", header = true, partName = "password")
        String password,
        @WebParam(name = "tokenvalue", targetNamespace = "http://webservice.service.soap.com/", header = true, mode = WebParam.Mode.OUT, partName = "tokenvalue")
        Holder<String> tokenvalue);

    /**
     * 
     * @param counter
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "countAsync", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.CountAsync")
    @Action(input = "http://webservice.service.soap.com/MobileService/countAsync")
    public void countAsync(
        @WebParam(name = "counter", targetNamespace = "")
        int counter);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.GreetResponse")
    @Action(input = "http://webservice.service.soap.com/MobileService/greetRequest", output = "http://webservice.service.soap.com/MobileService/greetResponse")
    public String greet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param subscriberNumber
     */
    @WebMethod(action = "delete")
    @RequestWrapper(localName = "deleteSubscriber", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.DeleteSubscriber")
    @ResponseWrapper(localName = "deleteSubscriberResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.DeleteSubscriberResponse")
    @Action(input = "delete", output = "http://webservice.service.soap.com/MobileService/deleteSubscriberResponse")
    public void deleteSubscriber(
        @WebParam(name = "subscriberNumber", targetNamespace = "http://custom.namespace.com")
        String subscriberNumber);

    /**
     * 
     * @return
     *     returns com.soap.client.mobilewebservice.clientgen.SubscriberData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDummySubscriber", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.GetDummySubscriber")
    @ResponseWrapper(localName = "getDummySubscriberResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.GetDummySubscriberResponse")
    @Action(input = "http://webservice.service.soap.com/MobileService/getDummySubscriberRequest", output = "http://webservice.service.soap.com/MobileService/getDummySubscriberResponse")
    public SubscriberData getDummySubscriber();

    /**
     * 
     * @return
     *     returns java.util.List<com.soap.client.mobilewebservice.clientgen.SubscriberData>
     */
    @WebMethod
    @WebResult(name = "Subscriber", targetNamespace = "")
    @RequestWrapper(localName = "getAllSubscribers", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.GetAllSubscribers")
    @ResponseWrapper(localName = "getAllSubscribersResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.GetAllSubscribersResponse")
    @Action(input = "http://webservice.service.soap.com/MobileService/getAllSubscribersRequest", output = "http://webservice.service.soap.com/MobileService/getAllSubscribersResponse")
    public List<SubscriberData> getAllSubscribers();

    /**
     * 
     * @param subscriberNumber
     * @return
     *     returns com.soap.client.mobilewebservice.clientgen.SubscriberData
     */
    @WebMethod
    @WebResult(name = "createSubscriberSecureResponse", targetNamespace = "")
    @RequestWrapper(localName = "findSubscriber", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.FindSubscriber")
    @ResponseWrapper(localName = "findSubscriberResponse", targetNamespace = "http://webservice.service.soap.com/", className = "com.soap.client.mobilewebservice.clientgen.FindSubscriberResponse")
    @Action(input = "http://webservice.service.soap.com/MobileService/findSubscriberRequest", output = "http://webservice.service.soap.com/MobileService/findSubscriberResponse")
    public SubscriberData findSubscriber(
        @WebParam(name = "subscriberNumber", targetNamespace = "")
        String subscriberNumber);

}
