
package com.soap.client.mobilewebservice.clientgen;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SecurityException", targetNamespace = "http://webservice.service.soap.com/")
public class SecurityException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SecurityException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SecurityException_Exception(String message, SecurityException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SecurityException_Exception(String message, SecurityException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.soap.client.mobilewebservice.clientgen.SecurityException
     */
    public SecurityException getFaultInfo() {
        return faultInfo;
    }

}
