
package com.soap.client.addressing.clientgen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddressPortType", targetNamespace = "http://address.service.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressPortType {


    /**
     * 
     * @param subscriberNumber
     * @return
     *     returns com.soap.client.addressing.clientgen.SubscriberData
     */
    @WebMethod
    @WebResult(name = "GetSubscriber", targetNamespace = "")
    @RequestWrapper(localName = "findSubscriber", targetNamespace = "http://address.service.soap.com/", className = "com.soap.client.addressing.clientgen.FindSubscriber")
    @ResponseWrapper(localName = "findSubscriberResponse", targetNamespace = "http://address.service.soap.com/", className = "com.soap.client.addressing.clientgen.FindSubscriberResponse")
    @Action(input = "http://address.service.soap.com/AddressPortType/findSubscriberRequest", output = "http://address.service.soap.com/AddressPortType/findSubscriberResponse")
    public SubscriberData findSubscriber(
        @WebParam(name = "subscriberNumber", targetNamespace = "")
        String subscriberNumber);

}
