
package com.soap.client.addressing.clientgen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomAddressService", targetNamespace = "http://address.service.soap.com/", wsdlLocation = "http://localhost:10001/SoapWS/CustomAddress?wsdl")
public class CustomAddressService
    extends Service
{

    private final static URL CUSTOMADDRESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMADDRESSSERVICE_EXCEPTION;
    private final static QName CUSTOMADDRESSSERVICE_QNAME = new QName("http://address.service.soap.com/", "CustomAddressService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10001/SoapWS/CustomAddress?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMADDRESSSERVICE_WSDL_LOCATION = url;
        CUSTOMADDRESSSERVICE_EXCEPTION = e;
    }

    public CustomAddressService() {
        super(__getWsdlLocation(), CUSTOMADDRESSSERVICE_QNAME);
    }

    public CustomAddressService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMADDRESSSERVICE_QNAME, features);
    }

    public CustomAddressService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMADDRESSSERVICE_QNAME);
    }

    public CustomAddressService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMADDRESSSERVICE_QNAME, features);
    }

    public CustomAddressService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomAddressService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddressPortType
     */
    @WebEndpoint(name = "AddressServicePort")
    public AddressPortType getAddressServicePort() {
        return super.getPort(new QName("http://address.service.soap.com/", "AddressServicePort"), AddressPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressPortType
     */
    @WebEndpoint(name = "AddressServicePort")
    public AddressPortType getAddressServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://address.service.soap.com/", "AddressServicePort"), AddressPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMADDRESSSERVICE_EXCEPTION!= null) {
            throw CUSTOMADDRESSSERVICE_EXCEPTION;
        }
        return CUSTOMADDRESSSERVICE_WSDL_LOCATION;
    }

}
