//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.01 at 05:17:37 PM IST 
//


package com.ericsson.mdc.ws.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestHeader" type="{http://mdc.ericsson.com/ws/soap/}requestHeader"/>
 *         &lt;element name="basicResourceDetails" type="{http://mdc.ericsson.com/ws/soap/}basicResourceDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestHeader",
    "basicResourceDetails"
})
@XmlRootElement(name = "updateBasicResourceDetailsRequest")
public class UpdateBasicResourceDetailsRequest {

    @XmlElement(required = true)
    protected RequestHeader requestHeader;
    @XmlElement(required = true)
    protected BasicResourceDetails basicResourceDetails;

    /**
     * Gets the value of the requestHeader property.
     * 
     * @return
     *     possible object is
     *     {@link RequestHeader }
     *     
     */
    public RequestHeader getRequestHeader() {
        return requestHeader;
    }

    /**
     * Sets the value of the requestHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestHeader }
     *     
     */
    public void setRequestHeader(RequestHeader value) {
        this.requestHeader = value;
    }

    /**
     * Gets the value of the basicResourceDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BasicResourceDetails }
     *     
     */
    public BasicResourceDetails getBasicResourceDetails() {
        return basicResourceDetails;
    }

    /**
     * Sets the value of the basicResourceDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicResourceDetails }
     *     
     */
    public void setBasicResourceDetails(BasicResourceDetails value) {
        this.basicResourceDetails = value;
    }

}
