
package com.soap.client.mobilewebservice.clientgen;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MobileWebService", targetNamespace = "http://webservice.service.soap.com/", wsdlLocation = "http://localhost:10002/SoapWS/Core/Mobile?wsdl")
public class MobileWebService
    extends Service
{

    private final static URL MOBILEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOBILEWEBSERVICE_EXCEPTION;
    private final static QName MOBILEWEBSERVICE_QNAME = new QName("http://webservice.service.soap.com/", "MobileWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10002/SoapWS/Core/Mobile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOBILEWEBSERVICE_WSDL_LOCATION = url;
        MOBILEWEBSERVICE_EXCEPTION = e;
    }

    public MobileWebService() {
        super(__getWsdlLocation(), MOBILEWEBSERVICE_QNAME);
    }

    public MobileWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOBILEWEBSERVICE_QNAME, features);
    }

    public MobileWebService(URL wsdlLocation) {
        super(wsdlLocation, MOBILEWEBSERVICE_QNAME);
    }

    public MobileWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOBILEWEBSERVICE_QNAME, features);
    }

    public MobileWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MobileService
     */
    @WebEndpoint(name = "MobilePort")
    public MobileService getMobilePort() {
        return super.getPort(new QName("http://webservice.service.soap.com/", "MobilePort"), MobileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileService
     */
    @WebEndpoint(name = "MobilePort")
    public MobileService getMobilePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.service.soap.com/", "MobilePort"), MobileService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOBILEWEBSERVICE_EXCEPTION!= null) {
            throw MOBILEWEBSERVICE_EXCEPTION;
        }
        return MOBILEWEBSERVICE_WSDL_LOCATION;
    }

}
