
package com.soap.client.mobilewebservice.clientgen;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MobileException", targetNamespace = "http://webservice.service.soap.com/")
public class MobileSubscriptionException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MobileSubscriptionException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MobileSubscriptionException_Exception(String message, MobileSubscriptionException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MobileSubscriptionException_Exception(String message, MobileSubscriptionException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.soap.client.mobilewebservice.clientgen.MobileSubscriptionException
     */
    public MobileSubscriptionException getFaultInfo() {
        return faultInfo;
    }

}
