
package com.app.client.stubs.subscriber;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SubscriberNotFoundException", targetNamespace = "http://service.mobile.com")
public class SubscriberNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SubscriberNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SubscriberNotFoundException_Exception(String message, SubscriberNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SubscriberNotFoundException_Exception(String message, SubscriberNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.app.client.stubs.subscriber.SubscriberNotFoundException
     */
    public SubscriberNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
