
package com.app.client.stubs.subscriber;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriberMobileService", targetNamespace = "http://impl.ws.app.com/", wsdlLocation = "http://localhost:9090/SubscriberManagement?wsdl")
public class SubscriberMobileService
    extends Service
{

    private final static URL SUBSCRIBERMOBILESERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIBERMOBILESERVICE_EXCEPTION;
    private final static QName SUBSCRIBERMOBILESERVICE_QNAME = new QName("http://impl.ws.app.com/", "SubscriberMobileService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/SubscriberManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBSCRIBERMOBILESERVICE_WSDL_LOCATION = url;
        SUBSCRIBERMOBILESERVICE_EXCEPTION = e;
    }

    public SubscriberMobileService() {
        super(__getWsdlLocation(), SUBSCRIBERMOBILESERVICE_QNAME);
    }

    public SubscriberMobileService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIBERMOBILESERVICE_QNAME, features);
    }

    public SubscriberMobileService(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIBERMOBILESERVICE_QNAME);
    }

    public SubscriberMobileService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIBERMOBILESERVICE_QNAME, features);
    }

    public SubscriberMobileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriberMobileService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriberService
     */
    @WebEndpoint(name = "SubscriberPort")
    public SubscriberService getSubscriberPort() {
        return super.getPort(new QName("http://impl.ws.app.com/", "SubscriberPort"), SubscriberService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriberService
     */
    @WebEndpoint(name = "SubscriberPort")
    public SubscriberService getSubscriberPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.app.com/", "SubscriberPort"), SubscriberService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIBERMOBILESERVICE_EXCEPTION!= null) {
            throw SUBSCRIBERMOBILESERVICE_EXCEPTION;
        }
        return SUBSCRIBERMOBILESERVICE_WSDL_LOCATION;
    }

}
